name: First workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Good morning from the first step."
      - name: Cya
        run: echo "cya from second step"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get user id
        run: id 
      - name: check pwd
        run: pwd
      - name: list files
        run: ls -ltr
      - name: run update
        run: sudo apt update
      - name: install jdk
        run: sudo apt install openjdk-11-jdk -y
      - name: install maven
        run: sudo apt install maven -y
      - name: check maven version
        run: java -version && mvn -version
      - name: clone vprofile
        run: git clone https://github.com/hkhcoder/vprofile-project.git && cd vprofile-project 
      - name: build
        run: mvn install
  
